version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # does it build context / project UI env-var reference
    steps:
      - run:
          name: suitcase build
          command: |
            echo 'Hello my people @ odk-x'
            echo 'This is the build pipeline'