version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - run:
          name: dependencies installation
          command: sudo apt-get update && sudo apt-get install -y ant maven 
      - run:
          name: suitcase build
          command: |
            cd dependencies
            ant
            cd ..
            mvn clean package
workflows:
  my-suitcase-build:
    jobs:
      - build