version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # project UI env-var reference
    steps:
      - run:
          name: suitcase build
          command: |
            cd dependencies
            ant
            cd ..
            mvn clean package
workflows:
  my-suitcase-build:
    jobs:
      - build