version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  #  build he context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: dependencies installation
          command: |
            sudo apt-get update && sudo apt-get install -y ant maven 
      - run:
          name: suitcase build
          command: |
            cd dependencies
            ant
            cd ..
            mvn clean package
workflows:
  my-suitcase-build:
    jobs:
      - build